name: Publish

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      # - name: Setup Node and github package registry
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      #     registry-url: https://npm.pkg.github.com/
      #     scope: "@letsbuilders"
